=== Dolf23/JD2016/src/by/it/telushko/jd02_07_project_plan/client.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT clients (client)+>
<!ELEMENT client (name,vehicle,email,phone)>
<!ATTLIST client login ID #REQUIRED password ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vehicle (brand,model,year)>
<!ATTLIST vehicle type motorcycle|car>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== Dolf23/JD2016/src/by/it/telushko/jd02_07_project_plan/сlient_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clients SYSTEM "D:\Students\Tel\JD2016\src\by\it\telushko\jd02_07_project_plan\client.dtd">
        <clients>

            <client login="login_1" password="pass_1">
                <name>Vladimir</name>>
                <vehicle type="motorcycle">
                    <brand>Kawasaki</brand>
                    <model>Z1000</model>
                    <year>2003</year>>
                </vehicle>
                <email>vladimir.telushko@gmail.com</email>
                <phone>+375 29 7570513</phone>
            </client>

            <client login="login_2" password="pass_2">
                <name>Valery</name>>
                <vehicle type="car">
                    <brand>Citroen</brand>
                    <model>C5</model>
                    <year>2005</year>>
                </vehicle>
                <email>valery.hetman@gmail.com</email>
                <phone>+375 29 5789179</phone>
            </client>

        </clients>
