=== Dolf23/JD2016/src/by/it/knyazev/JD02/less_07/some.dtd
<!ELEMENT body (registration)+>
        <!ELEMENT registration (main-date, minor-date, temp-date)>
        <!ATTLIST registration
                el ID #REQUIRED
                >
        <!ELEMENT main-date (username, e-mail, password)>
        <!ELEMENT username (#PCDATA)>
        <!ELEMENT e-mail (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT minor-date (location, about, links)>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT about (#PCDATA)>
        <!ELEMENT links (link,link,link)>
        <!ELEMENT link (#PCDATA)>
        <!ELEMENT temp-date (geo-location, key)>
        <!ELEMENT geo-location (#PCDATA)>
        <!ELEMENT key (#PCDATA)>

=== Dolf23/JD2016/src/by/it/knyazev/JD02/less_07/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE body SYSTEM "some.dtd" >
<body>
	<registration el="asd">
		<main-date>
			<username/>
			<e-mail/>
			<password/>
		</main-date>
		<minor-date>
			<location/>
			<about/>
			<links>
				<link/>
				<link/>
				<link/>
			</links>
		</minor-date>
		<temp-date>
			<geo-location/>
			<key/>
		</temp-date>
	</registration>
</body>
