=== Dolf23/JD2016/src/by/it/podelstchikova/Library/library.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT library (books,readers,libraryCards)+>

        <!ELEMENT books (book)+>
        <!ELEMENT book (nameBook,author,series,style,volumeBook,numberOfBook)>
        <!ATTLIST book login ID #REQUIRED>

        <!ELEMENT numberOfBook (#PCDATA)>
        <!ELEMENT nameBook (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT series (#PCDATA)>
        <!ELEMENT style (#PCDATA)>
        <!ELEMENT volumeBook (#PCDATA)>

        <!ELEMENT readers (reader)+>


        <!ELEMENT reader (name,telephone,numberOfTheLibraryCard)>
        <!ATTLIST reader login ID #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT numberOfTheLibraryCard (#PCDATA)>

        <!ELEMENT libraryCards (libraryCard)+>

        <!ELEMENT libraryCard (readerID,dateOfCapture,dateOfReturn,bookID)>
        <!ELEMENT readerID (#PCDATA)>
        <!ELEMENT bookID (#PCDATA)>
        <!ELEMENT dateOfCapture (#PCDATA)>
        <!ELEMENT dateOfReturn (#PCDATA)>
        <!ATTLIST libraryCard login #REQUIRED>

=== Dolf23/JD2016/src/by/it/podelstchikova/Library/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library SYSTEM
        "library.dtd">
<library>

    <books>
        <book login="IDB1">
             <nameBook>
                1
             </nameBook>
             <author>
                1
             </author>
             <series>
                1
             </series>
             <style>
                1
             </style>
             <volumeBook>
                1
             </volumeBook>
             <numberOfBook>
                 1
             </numberOfBook>
        </book>
    </books>

    <readers >
        <reader login="IDR1">
        <name>
            1
        </name>
        <telephone>
            1
        </telephone>
        <numberOfTheLibraryCard>
            1
        </numberOfTheLibraryCard>
        </reader>
    </readers>

    <libraryCards >
        <libraryCard login="IDLC1">
             <readerID>
                1
             </readerID>
             <dateOfCapture>
                1
             </dateOfCapture>
             <dateOfReturn>
                1
             </dateOfReturn>
             <bookID>
                1
             </bookID>
         </libraryCard>
    </libraryCards>
</library>
