=== Dolf23/JD2016/src/by/it/zhuravlyov/LD02_07/element.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cars (auto)+>
      <!ATTLIST auto
         id ID #REQUIRED>
        <!ELEMENT auto (brand,year,fuel,mileage,Transmission)>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT fuel (#PCDATA)>
        <!ELEMENT mileage (#PCDATA)>
        <!ELEMENT Transmission (#PCDATA)>

=== Dolf23/JD2016/src/by/it/zhuravlyov/LD02_07/XML+DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cars SYSTEM "element.dtd" >
<cars>
    <auto id="marks">
        <brand>BMW 3 series</brand>
        <year>2005</year>
        <fuel>petrol</fuel>
        <mileage>12000</mileage>
        <Transmission>mechanical</Transmission>
    </auto>

    <auto id="mazda">
        <brand>mazda 6</brand>
        <year>2011</year>
        <fuel>petrol</fuel>
        <mileage>20000</mileage>
        <Transmission>automatic</Transmission>
    </auto>

    <auto id="audi">
        <brand>audi TT</brand>
        <year>2010</year>
        <fuel>petrol</fuel>
        <mileage>90000</mileage>
        <Transmission>mechanical</Transmission>
    </auto>

    <auto id="toyota">
    <brand>Toyota tundra</brand>
    <year>2013</year>
    <fuel>petrol</fuel>
    <mileage>180000</mileage>
    <Transmission>automatic</Transmission>
    </auto>
</cars>
